language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: npm
  email: $ADMIN_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true